name: Docker_workflow
on:
  push:
    tags:
      - "v*"
jobs:
  main_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.7.0

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/randnum:${{ github.ref }}

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: Obi-wan \n Matriculation: 404 \n Email: 404 \n Repo: 404 \n Image name: 404 \n Image url: https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

          
